distances: 
    Screw1Bottom: 
        Screw2Bottom: 5
        Screw1Top: 8.1
        Screw1Nut: 6.1
        Screw3Bottom: 7
        Screw4Bottom: 10
    
    Screw1Nut:
        Screw4Top: 10
        Screw1Top: 2
    
    Screw2Bottom:
        Screw3Bottom: 2
        Screw4Bottom: 5
    
    Screw2Top:
        Screw1Top: 7.7
        Screw3Top: 1.9
    
    Screw3Bottom:
        Screw4Bottom: 3
    
    Screw3Top:
        Screw4Top: 4.6
    
    Screw4Bottom:
        Screw4Top: 6.1
    
    X1:
        MazeCornerOpenLeft: 9.4
        X2: 16.8
    
    X2:
        MazeCornerClosedLeft: 17.4

#calculates angle at the first given marker
angles:
    MazeCornerOpenLeft: 
        value: 90
        marker: [MazeCornerOpenLeft, MazeCornerOpenRight, MazeCornerClosedLeft]

    MazeCornerOpenRight: 
        value: 90
        marker: [MazeCornerOpenRight, MazeCornerOpenLeft, MazeCornerClosedRight]

    MazeCornerClosedLeft: 
        value: 90
        marker: [MazeCornerClosedLeft, MazeCornerClosedRight, MazeCornerOpenLeft]
    
    MazeCornerClosedRight: 
        value: 90
        marker: [MazeCornerClosedRight, MazeCornerClosedLeft, MazeCornerOpenRight]
        
    Screw1: 
        value: 90
        marker: [Screw1Bottom, Screw1Top, MazeCornerClosedRight, MazeCornerClosedLeft, MazeCornerOpenRight]  

    Screw2: 
        value: 90
        marker: [Screw2Bottom, Screw2Top, MazeCornerClosedRight, MazeCornerClosedLeft, MazeCornerOpenRight]

    Screw3: 
        value: 90
        marker: [Screw3Bottom, Screw3Top, MazeCornerClosedRight, MazeCornerClosedLeft, MazeCornerOpenRight]

    Screw4: w
        value: 90
        marker: [Screw4Bottom, Screw4Top, MazeCornerClosedRight, MazeCornerClosedLeft, MazeCornerOpenRight]