distances: 
    screw1_bottom: 
        screw2_bottom: 5
        screw1_top: 8.1
        screw1_nut: 6.1
        screw3_bottom: 7
        screw4_bottom: 10
    
    screw1_nut:
        screw4_top: 10
        screw1_top: 2
    
    screw2_bottom:
        screw3_bottom: 2
        screw4_bottom: 5
    
    screw2_top:
        screw1_top: 7.7
        screw3_top: 1.9
    
    screw3_bottom:
        screw4_bottom: 3
    
    screw3_top:
        screw4_top: 4.6
    
    screw4_bottom:
        screw4_top: 6.1
    
    x1:
        maze_corner_open_left: 9.4
        x2: 16.8
    
    x2:
        maze_corner_closed_left: 17.4

    maze_corner_open_left:
        maze_corner_closed_left: 50
        maze_corner_open_right: 5

    maze_corner_open_right:
        maze_corner_closed_right: 50
        maze_corner_open_left: 5

    maze_corner_closed_left:
        maze_corner_open_left: 50
        maze_corner_closed_right: 5
        maze_corner_open_right: 50.24

    maze_corner_closed_right:
        maze_corner_closed_left: 5
        maze_corner_open_right: 50
        maze_corner_open_left: 50.24





#calculates angle at the first given marker
angles:
    maze_corner_open_left: 
        value: 90
        marker: [maze_corner_open_left, maze_corner_open_right, maze_corner_closed_left]

    maze_corner_open_right: 
        value: 90
        marker: [maze_corner_open_right, maze_corner_open_left, maze_corner_closed_right]

    maze_corner_closed_left: 
        value: 90
        marker: [maze_corner_closed_left, maze_corner_closed_right, maze_corner_open_left]
    
    maze_corner_closed_right: 
        value: 90
        marker: [maze_corner_closed_right, maze_corner_closed_left, maze_corner_open_right]
        
    screw_1: 
        value: 90
        marker: [screw1_bottom, screw1_top, maze_corner_closed_right, maze_corner_closed_left, maze_corner_open_right]  

    screw_2: 
        value: 90
        marker: [screw2_bottom, screw2_top, maze_corner_closed_right, maze_corner_closed_left, maze_corner_open_right]

    screw_3: 
        value: 90
        marker: [screw3_bottom, screw3_top, maze_corner_closed_right, maze_corner_closed_left, maze_corner_open_right]

    screw_4: 
        value: 90
        marker: [screw4_bottom, screw4_top, maze_corner_closed_right, maze_corner_closed_left, maze_corner_open_right]

marker_ids_to_connect_in_3D_plot:
    -
      - screw1_bottom
      - screw4_bottom
      - screw4_top
      - screw1_nut
    -
      - maze_corner_closed_left
      - maze_corner_open_left
      - maze_corner_open_right
      - maze_corner_closed_right
