distances: 
    MazeCornerOpenLeft:
        MazeCornerClosedLeft: 50
        MazeCornerOpenRight: 5

    MazeCornerOpenRight:
        MazeCornerClosedRight: 50
        MazeCornerOpenLeft: 5

    MazeCornerClosedLeft:
        MazeCornerOpenLeft: 50
        MazeCornerClosedRight: 5
        MazeCornerOpenRight: 50.24

    MazeCornerClosedRight:
        MazeCornerClosedLeft: 5
        MazeCornerOpenRight: 50
        MazeCornerOpenLeft: 50.24

# calculates angle at the first given marker
angles:
    MazeCornerOpenLeft: 
        value: 90
        marker: [MazeCornerOpenLeft, MazeCornerOpenRight, MazeCornerClosedLeft]

    MazeCornerOpenRight: 
        value: 90
        marker: [MazeCornerOpenRight, MazeCornerOpenLeft, MazeCornerClosedRight]

    MazeCornerClosedLeft: 
        value: 90
        marker: [MazeCornerClosedLeft, MazeCornerClosedRight, MazeCornerOpenLeft]
    
    MazeCornerClosedRight: 
        value: 90
        marker: [MazeCornerClosedRight, MazeCornerClosedLeft, MazeCornerOpenRight]
    
    
marker_ids_to_connect_in_3D_plot:
    -
      - MazeCornerClosedLeft
      - MazeCornerOpenLeft
      - MazeCornerOpenRight
      - MazeCornerClosedRight
      - MazeCornerClosedLeft

unique_ids:
    - MazeCornerOpenLeft
    - MazeCornerOpenRight
    - MazeCornerClosedLeft
    - MazeCornerClosedRight
