#animal lines need to be strings
animal_lines:
- "196"
calibration_evaluation_path:
  Bottom: calevpath
  Ground1: skldks
  Ground2: lsdksl
  Side1: ksldks
  Side2: lsdks
  Top: ksldksd
calibration_evaluation_type:
  Bottom: TM
  Ground1: TM
  Ground2: TM
  Side1: TM
  Side2: TM
  Top: TM
intrinsic_calibration_dir: test_data/intrinsic_calibrations/
paradigms: 
- OTR
- OTT
- OTE
processing_path:
  Bottom: "/Users/kobel/Downloads/DLC_Netzwerke/OT_BottomCam_final-Konstantin-2022-09-20/config.yaml"
  Ground1: "/Users/kobel/Downloads/DLC_Netzwerke/OT_BottomCam_final-Konstantin-2022-09-20/config.yaml"
  Ground2: "/Users/kobel/Downloads/DLC_Netzwerke/OT_BottomCam_final-Konstantin-2022-09-20/config.yaml"
  Side1: "/Users/kobel/Downloads/DLC_Netzwerke/OT_SideCam_final-Konstantin-2022-09-07/config.yaml"
  Side2: "/Users/kobel/Downloads/DLC_Netzwerke/OT_SideCam_final-Konstantin-2022-09-07/config.yaml"
  Top: "/Users/kobel/Downloads/DLC_Netzwerke/OT_TopCam-final-Charlotte-2022-09-22/config.yaml"
processing_type:
  Bottom: DLC
  Ground1: DLC
  Ground2: DLC
  Side1: DLC
  Side2: DLC
  Top: DLC
led_extraction_type:
  Bottom: DLC
  Ground1: DLC
  Ground2: DLC
  Side1: DLC
  Side2: DLC
  Top: DLC
led_extraction_path:
  Bottom: "/Users/kobel/Downloads/DLC_Netzwerke/OT_BottomCam_final-Konstantin-2022-09-20/config.yaml"
  Ground1: "/Users/kobel/Downloads/DLC_Netzwerke/OT_BottomCam_final-Konstantin-2022-09-20/config.yaml"
  Ground2: "/Users/kobel/Downloads/DLC_Netzwerke/OT_BottomCam_final-Konstantin-2022-09-20/config.yaml"
  Side1: "/Users/kobel/Downloads/DLC_Netzwerke/OT_SideCam_final-Konstantin-2022-09-07/config.yaml"
  Side2: "/Users/kobel/Downloads/DLC_Netzwerke/OT_SideCam_final-Konstantin-2022-09-07/config.yaml"
  Top: "/Users/kobel/Downloads/DLC_Netzwerke/OT_TopCam-final-Charlotte-2022-09-22/config.yaml"
target_fps: 30
valid_cam_IDs:
- Bottom
- Top
- Side1
- Side2
- Ground1
- Ground2
load_calibration: True

# default values: only change, if you have to switch the computer
max_frames_to_write: 3000
max_calibration_frames: 300
use_gpu: False