CENTER: MazeCornerClosedLeft
REFERENCE_LENGTH_CM: 50
REFERENCE_LENGTH_MARKERS:
- MazeCornerClosedLeft
- MazeCornerOpenLeft
REFERENCE_ROTATION_COORDS:
- - 0
  - 0
  - 0
- - 0
  - 5
  - 0
- - 50
  - 5
  - 0
- - 50
  - 0
  - 0
REFERENCE_ROTATION_MARKERS:
- MazeCornerClosedLeft
- MazeCornerClosedRight
- MazeCornerOpenRight
- MazeCornerOpenLeft
EQUAL_LENGTHS_GROUND_TRUTH:
- - - MazeCornerClosedLeft
    - MazeCornerClosedRight
  - - MazeCornerOpenRight
    - MazeCornerOpenLeft
- - - MazeCornerClosedLeft
    - MazeCornerOpenLeft
  - - MazeCornerOpenRight
    - MazeCornerClosedRight
INVISIBLE_MARKERS:
 x: [0, 0, 0, 0, 0, 0, 0, 0]
 y: [0, 50, 50, 0, 0, 50, 50, 0]
 z: [0, 0, 0, 0, 50, 50, 50, 50]
# None, x, y, z
FLIP_AXIS_TO_ADJUST_CHIRALITY: z