name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: https://retune-commons.github.io/let_it_be_3D/
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: actions/checkout@main
